name: Bucket Minion
description: Set of actions to automate maintaining of bucket.
author: ScoopInstaller Maintainers
runs:
    using: docker
    image: Dockerfile
branding:
    icon: package
    color: purple
